DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM dba_users t WHERE t.username = 'FITNESS';
  IF v_count = 1 THEN 
    EXECUTE IMMEDIATE 'DROP USER FITNESS CASCADE';
  END IF;
END;
/

CREATE USER FITNESS 
  IDENTIFIED BY "123" 
  DEFAULT TABLESPACE users
  QUOTA UNLIMITED ON users
;

GRANT CREATE SESSION TO FITNESS;
GRANT CREATE TABLE TO FITNESS;
GRANT CREATE VIEW TO FITNESS;
GRANT CREATE SEQUENCE TO FITNESS;
GRANT CREATE PROCEDURE TO FITNESS;
GRANT CREATE TRIGGER TO FITNESS;
GRANT ALTER ANY TRIGGER TO FITNESS;
GRANT CREATE TYPE TO FITNESS;




------------
DROP USER FITNESS CASCADE;
