-- USERS tábla trigger
CREATE OR REPLACE TRIGGER users_trg
BEFORE INSERT ON USERS
FOR EACH ROW
BEGIN
    IF :NEW.USER_ID IS NULL THEN
       :NEW.USER_ID := user_seq.NEXTVAL;
    END IF;
END;
/


-- WORKOUT_PLANS tábla trigger
CREATE OR REPLACE TRIGGER workout_plans_trg
BEFORE INSERT ON WORKOUT_PLANS
FOR EACH ROW
BEGIN
    IF :NEW.PLAN_ID IS NULL THEN
       :NEW.PLAN_ID := workout_plans_seq.NEXTVAL;
    END IF;
END;
/


-- WORKOUT_DAYS tábla trigger
CREATE OR REPLACE TRIGGER workout_days_trg
BEFORE INSERT ON WORKOUT_DAYS
FOR EACH ROW
BEGIN
    IF :NEW.DAY_ID IS NULL THEN
       :NEW.DAY_ID := workout_days_seq.NEXTVAL;
    END IF;
END;
/


-- WORKOUT_EXERCISES tábla trigger
CREATE OR REPLACE TRIGGER workout_exercises_trg
BEFORE INSERT ON WORKOUT_EXERCISES
FOR EACH ROW
BEGIN
    IF :NEW.EXERCISE_ID IS NULL THEN
       :NEW.EXERCISE_ID := workout_exercises_seq.NEXTVAL;
    END IF;
END;
/


-- WORKOUT_STATUS tábla trigger
CREATE OR REPLACE TRIGGER workout_status_trg
BEFORE INSERT ON WORKOUT_STATUS
FOR EACH ROW
BEGIN
    IF :NEW.STATUS_ID IS NULL THEN
       :NEW.STATUS_ID := workout_status_seq.NEXTVAL;
    END IF;
END;
/

-- USERS_LEVEL_GOAL tábla trigger
CREATE OR REPLACE TRIGGER users_level_goal_trg
BEFORE INSERT ON USERS_LEVEL_GOAL
FOR EACH ROW
BEGIN
    IF :NEW.LEVEL_GOAL_ID IS NULL THEN
       :NEW.LEVEL_GOAL_ID := users_level_goal_seq.NEXTVAL;
    END IF;
END;




--------
DROP TRIGGER workout_status_trg;
DROP TRIGGER TRG_WORKOUT_DAYS_ID;
DROP TRIGGER TRG_WORKOUT_PLANS_ID;
DROP TRIGGER TRG_USER_ID;
DROP TRIGGER TRG_WORKOUT_EXERCISES_ID;


SELECT TRIGGER_NAME
FROM USER_TRIGGERS;

